name: 部署 Tiddlywiki 静态页面到 Github Pages

on:
  push:
    branches:
      - main
      - master
#     paths:
#       - "plugins/**"
#       - "tiddlers/**"
#       - "package.json"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
          
      - name: 安装 NodeJS 依赖
        run: npm install
        
      # - name: 运行zx构建
      #   run: npm run zx-build

      - name: 构建在线版本网页
        run: npm run buildonline
      - name: 构建可下载离线版本的网页
        run: npm run buildoffline
      - name: Workbox 离线缓存
        run: npx workbox injectManifest workbox-config.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          # Upload entire repository
          path: ./public-dist
      - name: 部署到GitHub页面
        id: deployment
        uses: actions/deploy-pages@v2.0.2
